### ISSUE TITLE
Quickstart test not working

### ISSUE THREAD

**Issue by mrbluecoat** [pcollinson/nftfw#3]
I decided to throw together a quickstart test to try out nftfw.  Here are my findings and the two issues I encountered.

_All commands were run as root on a plain vanilla Debian Buster install._

`cat /etc/os-release | head -n 1`

> PRETTY_NAME="Debian GNU/Linux 10 (buster)"

```
apt -t buster-backports install -y git nftables python3-setuptools python3-pip python3-prettytable python3-wheel
cd /usr/local/src
git clone https://github.com/pcollinson/nftfw
cd nftfw
pip3 install .
cp Autoinstall.default Autoinstall.conf
bash Install.sh
cp cronfiles/cron-nftfw /etc/cron.d/nftfw
cp systemd/nftfw.* /etc/systemd/system
sed -i $'s/^;nftables_conf.*/nftables_conf = \/etc\/nftables.conf/' /usr/local/etc/nftfw/config.ini
nftfw -f -v load
```

> nftfw[1376]: Loading data from /usr/local/etc/nftfw
> nftfw[1376]: Problems with ftp-passive.sh, check files in /usr/local/etc/nftfw/rule.d with shell

I fixed the error by removing ftp-passive (which I don't need for my use case):

```
rm /usr/local/etc/nftfw/incoming.d/21-ftp-passive
rm /usr/local/etc/nftfw/rule.d/ftp-passive.sh
nftfw -f -v load
```

> nftfw[1401]: Loading data from /usr/local/etc/nftfw
> nftfw[1401]: Creating reference files in /usr/local/var/lib/nftfw/build.d
> nftfw[1401]: Test files using nft command
> nftfw[1401]: Testing nft rulesets from nftfw_init.nft
> nftfw[1401]: Determine required installation
> nftfw[1401]: Initial install needed
> nftfw[1401]: Full install forced
> nftfw[1401]: Saving backup file
> nftfw[1401]: Running full installation
> nftfw[1401]: Loading nft rulesets from nftfw_init.nft
> nftfw[1401]: Full installation succeeded
> nftfw[1401]: Removing backup file
> nftfw[1401]: Install rules in /etc/nftables.conf

Prerequisite for my testing: `apt install -y dnsutils`

`curl -s example.com -o /dev/null && echo 'Test 1/2: Pass' || echo 'Test 1/2: Fail'`

> Test 1/2: Pass

```
touch /usr/local/etc/nftfw/blacklist.d/$(dig +short example.com)
nftfw -f -v load
nft list ruleset
```

> table ip filter {
>         set b_all {
>                 type ipv4_addr
>                 flags interval
>                 elements = { 93.184.216.34 }
>         }
> 
>         chain input {
>                 type filter hook input priority filter; policy drop;
>                 iif "lo" counter packets 0 bytes 0 accept
>                 ct state { established, related } counter packets 38 bytes 3064 accept
>                 ct state invalid counter packets 0 bytes 0 drop
>                 counter packets 2 bytes 394 jump whitelist
>                 counter packets 2 bytes 394 jump blacknets
>                 counter packets 2 bytes 394 jump blacklist
>                 counter packets 2 bytes 394 jump incoming
>         }
> 
> ...
> 
>         chain blacklist {
>                 ip saddr @b_all counter packets 0 bytes 0 log prefix "Blacklist " jump rejectcounter
>         }
> 
> ...
> 
> table ip6 filter {
> 
> ...
> 
>         chain blacklist {
>         }
> 
> ...

```
systemctl enable nftables
systemctl start nftables
systemctl enable nftfw.path
systemctl start nftfw.path

curl -s example.com -o /dev/null && echo 'Test 2/2: Fail' || echo 'Test 2/2: Pass'
```

> Test 2/2: Fail

I would expect example.com to not load since I added its IP address in the blocklist folder.  Is it possibly blocking on IPv4 but getting through on IPv6?  Ideally, I'd like to block all IPv6 since I don't need it for my use case.

I'm probably missing something obvious -- thanks in advance for your help  :)

**Comment by pcollinson** [comment]
Hmm. Well if you are attempting to stop people on your machine getting to _example.com_, then I would expect the IP to be put in the outgoing.d directory. That being said.

When you run the _curl_ command, your machine connects to example.com and this creates a connection, further inbound packets in the conversation are deemed to be 'RELATED' or 'CONNECTED'. The default setting for _nftfw_ is to accept these packets immediately with no further checking. 

This is because you want to block initial connections and it's more efficient to just look at the first packet in an inbound sequence, and block it then. There's no mileage in wasting CPU cycles in looking at loads of packets that are from non-blocked sources.

This is the default setup - aiming to efficiently stop bad guys getting in. However, there are disadvantages, if you decide to block an IP during a ongoing connection, and the connection remains open, then the bad guy doesn't get kicked off the machine until they try to reconnect. My judgement is that I am willing to pay this price, because I think that the cost of scanning every packet outweighs the inconvenience of getting rid of the bad guy immediately.

 However, this default is not wired into _nftfw_ code, it's defined in the _nftfw_init.nft_ template file and you are at liberty to change that to insert your own testing behaviour. 

I hope this assists. I'll take a look at the ftp-passive issue.

**Comment by pcollinson** [comment]
The ftp-passive script is intended to work with pure-ftp - and looked at a configuration file. It didn't test if the file existed and died. This is fixed. However, the rule does need hand editing for use with other ftp implementations - and actually has only been tested with pure-ftp.

Version 0.7.4 includes fixes to Install.sh for the shell problem and also for ftp-passive.sh.

**Comment by mrbluecoat** [comment]
`sh Install.sh` now works - thanks!  However `nftfw -f -v load` now gives me:

```
nftfw[19894]: Loading data from /usr/local/etc/nftfw
nftfw[19894]: Creating reference files in /usr/local/var/lib/nftfw/build.d
nftfw[19894]: Test files using nft command
nftfw[19894]: Testing nft rulesets from nftfw_init.nft
nftfw[19894]: nft using /usr/local/var/lib/nftfw/build.d/nftfw_init.nft: failed
nftfw[19894]: mnl.c:43: Unable to initialize Netlink socket: Protocol not supported

nftfw[19894]: Test failed using nftfw_init.nft
```

**Comment by pcollinson** [comment]
Google says - 'a reboot is needed'

**Comment by pcollinson** [comment]
or perhaps you were not running as root?

**Comment by mrbluecoat** [comment]
Thanks for your help.  Here's the version that worked:

```
apt -t buster-backports install -y git nftables python3-setuptools python3-pip python3-prettytable python3-wheel
cd /usr/local/src
git clone https://github.com/pcollinson/nftfw
cd nftfw
pip3 install .
cp Autoinstall.default Autoinstall.conf
sh Install.sh
cp cronfiles/cron-nftfw /etc/cron.d/nftfw
cp systemd/nftfw.* /etc/systemd/system
sed -i $'s/^;nftables_conf.*/nftables_conf = \/etc\/nftables.conf/' /usr/local/etc/nftfw/config.ini
reboot
```
```
curl -s example.com -o /dev/null && echo 'Test 1/2: Pass' || echo 'Test 1/2: Fail'
echo $(dig +short example.com) >> /usr/local/etc/nftfw/outgoing.d/42-80
nftfw -f -v load
systemctl enable nftables
systemctl start nftables
systemctl enable nftfw.path
systemctl start nftfw.path
curl -s example.com -o /dev/null && echo 'Test 2/2: Fail' || echo 'Test 2/2: Pass'
```
